### ISSUE TITLE
Install fails with v26

### ISSUE THREAD

**Issue by esunar** [esunar/test-repo#201]
graylog-26 does not install properly, always yielding the following stack trace:

unit-graylog-2: 10:41:18 ERROR unit.graylog/2.juju-log Hook error:                 
Traceback (most recent call last):                     
  File "/var/lib/juju/agents/unit-graylog-2/.venv/lib/python3.6/site-packages/charms/reactive/__init__.py", line 73, in main
    bus.dispatch(restricted=restricted_mode)                      
  File "/var/lib/juju/agents/unit-graylog-2/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 390, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-graylog-2/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 359, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-graylog-2/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 181, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-graylog-2/charm/reactive/graylog.py", line 36, in update_config
    configure_nagios()
TypeError: configure_nagios() missing 1 required positional argument: 'nagios'

This does not happen with v25

I'd wager this is a regression introduced by 6f21b446757ae951849f098c867bc5cbb885993a, since that commit adds a call to configure_nagios() as part of update_config(), regardless of the actual availability of a nrpe endpoint.
